/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseConfirmDialog: typeof import('./src/components/ui/BaseConfirmDialog.vue')['default']
    BaseInput: typeof import('./src/components/ui/BaseInput.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ControlCard: typeof import('./src/components/controls/ControlCard.vue')['default']
    ControlForm: typeof import('./src/components/controls/ControlForm.vue')['default']
    DeploymentCard: typeof import('./src/components/deployments/DeploymentCard.vue')['default']
    DeploymentContextMenu: typeof import('./src/components/deployments/DeploymentContextMenu.vue')['default']
    DeploymentForm: typeof import('./src/components/deployments/DeploymentForm.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImportCollisionDialog: typeof import('./src/components/ui/ImportCollisionDialog.vue')['default']
    LogViewer: typeof import('./src/components/controls/LogViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceControlItem: typeof import('./src/components/controls/ServiceControlItem.vue')['default']
    ServiceSelectDialog: typeof import('./src/components/ui/ServiceSelectDialog.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StepItem: typeof import('./src/components/deploy/StepItem.vue')['default']
    StepList: typeof import('./src/components/deploy/StepList.vue')['default']
    TagBadge: typeof import('./src/components/ui/TagBadge.vue')['default']
    TerminalPanel: typeof import('./src/components/deploy/TerminalPanel.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
